image:
  file: .gitpod.dockerfile
tasks:
  - name: Continuous Build
    command: |
      cd /workspace/xbvr
      yarn install && yarn build && go mod download github.com/ProtonMail/go-appdir && go generate && go get
      yarn dev
ports:
  - port: 9999
    onOpen: open-preview
  - port: 1338
    onOpen: ignore
  - port: 9998
    onOpen: ignore
